# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 598c9bc301c49222590540f91a0f1e08d3b3779df0f58196442321c6b7d9c2f5cedcf74ef61ef71b0c6bd215fe92694ef3c68c14fd1ed0335c6b76f549c65745

test:
  secret_key_base: da2019326673dc9cdf6402b3eb9e0e774f9e5e6820ef68e315f2be816caf33b021a9a273e393e88bc7155c5c304d8851a032e0e146d6562b6de2e10c96f32ade

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
